# Generated by Django 5.2.8 on 2025-11-26 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Alumno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(default='Nombre', max_length=100)),
                ('apellido', models.CharField(default='Apellido', max_length=100)),
                ('dni', models.CharField(blank=True, max_length=20, null=True)),
                ('email', models.EmailField(default='sinemail@example.com', max_length=254, unique=True)),
                ('fecha_nacimiento', models.DateField(blank=True, null=True)),
                ('carrera', models.CharField(choices=[('sistemas', 'Ingeniería en Sistemas'), ('industrial', 'Ingeniería Industrial'), ('civil', 'Ingeniería Civil')], default='sistemas', max_length=100)),
                ('promedio', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=4, null=True)),
            ],
        ),
    ]
