# Generated by Django 5.2.8 on 2025-11-26 20:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('alumnos', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='alumno',
            name='dni',
        ),
    ]
